language: node_js
node_js:
  - "11"
cache:
  directories:
    - "node_modules"
  yarn: true
script:
  - yarn build
  - yarn lint
  - yarn inject
deploy:
  on:
    branch: master
  edge: true
  provider: bluemixcloudfoundry
  username: $BX_USER
  password: $BX_PASS
  organization: ajdaniel
  space: prod
  manifest: Manifest.yml
  region: eu-gb